# Generated by Django 4.2.3 on 2023-09-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibit',
            options={'verbose_name_plural': 'Экспонаты'},
        ),
        migrations.AlterModelOptions(
            name='exhibittags',
            options={'verbose_name_plural': 'Теги экспонатов'},
        ),
        migrations.AlterModelOptions(
            name='exposition',
            options={'verbose_name_plural': 'Экспозиции'},
        ),
        migrations.AlterModelOptions(
            name='expositionexhibits',
            options={'verbose_name_plural': 'Экспонаты экспозиций'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name_plural': 'Залы музея'},
        ),
        migrations.AlterModelOptions(
            name='statuses',
            options={'verbose_name_plural': 'Перечень статусов'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Перечень тегов'},
        ),
    ]
