# Generated by Django 4.2.3 on 2023-09-02 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_exhibit_options_alter_exhibittags_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Перечень статусов',
                'db_table': 'tickets',
            },
        ),
        migrations.AddField(
            model_name='exhibit',
            name='exhibit_picture',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='exposition',
            name='exposition_picture',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='expositionexhibits',
            name='id_exhibit_exposition',
            field=models.OneToOneField(db_column='id_exhibit_exposition', on_delete=django.db.models.deletion.DO_NOTHING, to='main_page.exhibit'),
        ),
    ]
